### ISSUE TITLE
[<SDK or UI or UI-REACT or PROTOCOL>]: <description>

### ISSUE THREAD

**Issue by moltea** [ton-connect/sdk#175]
### Describe the bug

Can't reconnect wallet normally after tonConnectUI.disconnect();

### Expected behavior

The wallet connects the first time and transactions are sent successfully.

### Current behavior

After steps in "Steps to Reproduce"
I get:
`solid.js:894 Uncaught (in promise) Error: Unknown error
    at Wt (solid.js:894:10)
    at jt (solid.js:900:9)
    at solid.js:653:5
    at Lt (solid.js:623:18)
    at Ot (solid.js:725:7)
    at Pt (solid.js:823:36)
    at solid.js:792:34
    at Mt (solid.js:741:17)
    at solid.js:792:17
    at Mt (solid.js:742:5)`
The wallet does not connect, the qr code remains. If I scan the qr code a second time, the wallet seems to be linked, but when I try to send the transaction via sendTransaction, it simply does not appear in the wallet (tonkeeper and etc).

### Steps to Reproduce

Connected tonkeeper wallet (or any other available wallet) via connectWallet method
Used tonConnectUI.disconnect();
Trying to connect wallet again, and scan the qr-code. 

### Environment

latest tonconnect/ui from unpkg
OS: any
Browser: any

### Additional context

If i call connectWallet(), then i reload the pag and call connectWallet() again, then everything will be fine, the wallet will be linked the first time and transactions will be sent.

**Comment by nsake** [comment]
The thing

**Comment by Cassiana5kerber** [comment]
Queridos, estou iniciando essa nova fase evolutiva, e só sei o que me
lembro, por enquanto... do comando do prompt doc. da tela escura do
windons... então se alguem estiver disposto a me help segue meu whats.. +55
48 998298461. Agradecida.

Em quinta-feira, 25 de julho de 2024, Nikita Miniailo <
***@***.***> escreveu:

**Comment by meri-maki** [comment]
Looks like I have the same, because I have ton connect ui sdk errors, which I do not know how to handle
but the qr code remains and I sometimes see **Back to undefined** in Wallet app

**Comment by HipsterCat** [comment]
same

**Comment by asymptotee** [comment]
same

**Comment by asymptotee** [comment]
<img width="798" alt="image" src="https://github.com/user-attachments/assets/6e5490b2-a9ea-4d13-b7a1-171cd48aa13a" />

**Comment by rashdeva** [comment]
if somebody stucks with such problem in nextjs, just DO NOT USE server redirect.

**Comment by jenshenJ** [comment]
https://github.com/ton-connect/demo-dapp-with-next you can check our implementation of dapp in next. Reopen issue if you still have this problem
