### ISSUE TITLE
[UI]: How to catch the `TON_CONNECT_SDK_ERROR` error?

### ISSUE THREAD

**Issue by bchevalier** [ton-connect/sdk#202]
### Your Question

My application is triggering tons of `TON_CONNECT_SDK_ERROR` errors with the message `Operation aborted`.
However, those are all uncaught promise exceptions. How can I catch them to handle them properly?

Here is the code of the application, note that I am handling errors in the status change:
```js
    this.tonConnectUI = new TonConnectUI({
      manifestUrl: `${myUrl}/tonconnect-manifest.json`,
    });

    this.tonConnectUI.onStatusChange(
      async (status: ConnectedWallet | null) => onStatusChange,
      (error: TonConnectError) => {
        trackError('WalletConnectError', {
          name: error.name,
          message: error.message,
        });
      },
   ```

### Documentation Check

- [X] Yes, I have checked the documentation.

**Comment by Sotatek-CanPham** [comment]
same issue in Nextjs

**Comment by zapletnev** [comment]
The same

**Comment by abhiyana** [comment]
Did you get any solution? I am facing same issue.

**Comment by bchevalier** [comment]
@abhiyana 

One possible way to catch it is by using the javascript `unhandledrejection` event and identifying the ton connect sdk error:
```
function isTonConnectSdkError(error: Error | string) {
  const tonConnectError = 'TON_CONNECT_SDK';
  if (typeof error === 'string') {
    return error.includes(tonConnectError);
  }

  return error.message?.includes(tonConnectError);
}

window.addEventListener('unhandledrejection', function (rejection: PromiseRejectionEvent) {
  // handle rejection
  if (isTonConnectSdkError(rejection.reason)) {
    // ignore TonConnect sdk errors, they are handlded by sentry
    return;
  }
});
```

It's not ideal though because it does not prevent third party dependencies from catching those unhandled promise errors as well (such as analytics or error aggregation components).

**Comment by SharmilaBlessy27** [comment]
Hi everyone,

I’m using the tonconnect/ui-react package to trigger wallet connections in my project. The wallet connection is established successfully, but after 5 to 10 minutes, I start seeing the following error:

[TON_CONNECT_SDK_ERROR] TonConnectError
Operation aborted
Error: Operation aborted
    at abortController.signal.addEventListener.once (http://localhost:3000/static/js/bundle.js:64575:14)
    at signal.addEventListener.once (http://localhost:3000/static/js/bundle.js:64414:108)
    ...

Initially, everything works fine, but after some time, this error pops up. It seems to be related to the connection aborting after a certain amount of inactivity.

Has anyone encountered this issue or knows what could be causing the connection to abort after a delay? 
Please any one help me to resolve this?

**Comment by khanhhaquang** [comment]
<img width="341" alt="image" src="https://github.com/user-attachments/assets/e83a4986-ab11-4472-b0b2-d738aa8a8452">

**Comment by chengxianlov** [comment]
the same
![image](https://github.com/user-attachments/assets/51db5990-bf44-4595-b8a8-6552a73cff9c)

**Comment by meri-maki** [comment]
same thing i want to implement
cannot catch TonConnectUIProvider errors.....

**Comment by Tvenus** [comment]
The same

**Comment by minhkhoi8888** [comment]
the same

**Comment by runi-k** [comment]
same issue

**Comment by SaeedSoheili** [comment]
i have same issue

**Comment by Tvenus** [comment]
I solved that problem.

**Comment by uintptrs** [comment]
> I solved that problem.

Would you share the step's you taken for solving this issue?

**Comment by suraj978284** [comment]
> <img alt="image" width="341" src="https://private-user-images.githubusercontent.com/28600535/372074017-e83a4986-ab11-4472-b0b2-d738aa8a8452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwOTE4MjksIm5iZiI6MTczNzA5MTUyOSwicGF0aCI6Ii8yODYwMDUzNS8zNzIwNzQwMTctZTgzYTQ5ODYtYWIxMS00NDcyLWIwYjItZDczOGFhOGE4NDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDA1MjUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MmZjYzAwN2E1ZWRiYzViZWFhNGIzMjFkMWJlYzczOTgzM2Y5OWFhNjk2Yjg0MzM3ZmU2MTBmOTc0MjE5OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kCwTl3_Edz5mYZTj1KKyvEG71Pc0-_UWS8iBrlpGHbg">

This works, thanks.

**Comment by danikula** [comment]
same same

**Comment by Omokami** [comment]
@Tvenus 
Great!

**Comment by meri-maki** [comment]
the image in "this works" comment is unaccessible, the issue still persists

**Comment by root9464** [comment]
```
 function isTonConnectSdkError(error: Error | string) {
    const tonConnectError = 'Error: [TON_CONNECT_SDK_ERROR] TonConnectError';
    if (typeof error === 'string') {
      return error.includes(tonConnectError);
    }

    return error.message?.includes(tonConnectError);
  }

  useLayoutEffect(() => {
    window.addEventListener('unhandledrejection', function (rejection: PromiseRejectionEvent) {
      if (isTonConnectSdkError(rejection.reason)) {
        return;
      }
    });
  }, []);
```

I've done something similar before in this way
