### ISSUE TITLE
Unhandled errors

### ISSUE THREAD

**Issue by websashka** [ton-connect/sdk#21]
`Uncaught (in promise) Error: [TON_CONNECT_SDK_ERROR] Reject request
    at ConnectErrorsParser.parseError (index.js:2720:12)
    at TonConnect.onWalletConnectError (index.js:3756:39)
    at TonConnect.walletEventsListener (index.js:3727:14)
    at index.js:3358:46
    at Array.forEach (<anonymous>)
    at InjectedProvider.<anonymous> (index.js:3358:24)
    at Generator.next (<anonymous>)
    at fulfilled (index.js:3254:24)`

`Uncaught (in promise) Error: [TON_CONNECT_SDK_ERROR] Wallet declined the request
    at ConnectErrorsParser.parseError (index.js:2720:12)
    at TonConnect.onWalletConnectError (index.js:3756:39)
    at TonConnect.walletEventsListener (index.js:3727:14)
    at index.js:3190:44
    at Array.forEach (<anonymous>)
    at BridgeProvider.<anonymous> (index.js:3190:22)
    at Generator.next (<anonymous>)
    at index.js:3071:67
    at new Promise (<anonymous>)
    at __awaiter$4 (index.js:3053:10)`

`Uncaught (in promise) Error: [TON_CONNECT_SDK_ERROR] Close PopUp
    at ConnectErrorsParser.parseError (index.js:2720:12)
    at TonConnect.onWalletConnectError (index.js:3756:39)
    at TonConnect.walletEventsListener (index.js:3727:14)
    at index.js:3358:46
    at Array.forEach (<anonymous>)
    at InjectedProvider.<anonymous> (index.js:3358:24)
    at Generator.next (<anonymous>)
    at fulfilled (index.js:3254:24)`

**Comment by siandreev** [comment]
Hi @websashka, could you provide more details about the problem?
