### ISSUE TITLE
[UI-REACT]: Doen't working on Next.JS 15

### ISSUE THREAD

**Issue by jus1d** [ton-connect/sdk#290]
### Describe the bug

App throws random error when using Next.JS 15 and React 19

### Expected behavior

Expected to work

### Current behavior

Dont work

### Steps to Reproduce

1. Run `npx create-next-app@latest` and install `@tonconnect/ui-react`
2. Project won't start

### Environment

It simply doesnt install with React 19, using React 18 and Next 15 - installs but dont work

**Comment by Kennix88** [comment]
When will the problem be solved?

**Comment by antemikulic98** [comment]
is this still not solved??

**Comment by Hacedor2003** [comment]
the same

**Comment by justice-sh** [comment]
I have also experienced the same issue. It fails build on Next.js 15.1.6 and React 19.

This is the error I get:

`TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
    at C:\JProjects\codex\client\.next\server\app\(app)\dapp\(launchpad)\jetton\page.js:1072:23172
    at 15443 (C:\JProjects\codex\client\.next\server\app\(app)\dapp\(launchpad)\jetton\page.js:1072:23587)
    at Object.t [as require] (C:\JProjects\codex\client\.next\server\webpack-runtime.js:1:143)
    at require (C:\JProjects\codex\client\node_modules\.pnpm\next@15.1.6_@babel+core@7.2_fe117a173e182fd46a9fbb6f4e6c3de4\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:131:7946)
    at u (C:\JProjects\codex\client\node_modules\.pnpm\next@15.1.6_@babel+core@7.2_fe117a173e182fd46a9fbb6f4e6c3de4\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:36:646)
    at F (C:\JProjects\codex\client\node_modules\.pnpm\next@15.1.6_@babel+core@7.2_fe117a173e182fd46a9fbb6f4e6c3de4\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:36:10477)
    at W (C:\JProjects\codex\client\node_modules\.pnpm\next@15.1.6_@babel+core@7.2_fe117a173e182fd46a9fbb6f4e6c3de4\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:36:13033)
    at C:\JProjects\codex\client\node_modules\.pnpm\next@15.1.6_@babel+core@7.2_fe117a173e182fd46a9fbb6f4e6c3de4\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:36:15283
    at Z._fromJSON (C:\JProjects\codex\client\node_modules\.pnpm\next@15.1.6_@babel+core@7.2_fe117a173e182fd46a9fbb6f4e6c3de4\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:36:15317)
    at JSON.parse (<anonymous>)
Export encountered an error on /(app)/dapp/(launchpad)/jetton/page: /dapp/jetton, exiting the build.
 ⨯ Static worker exited with code: 1 and signal: null
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by ElliotWood13** [comment]
https://github.com/ton-connect/sdk/issues/216#issuecomment-2540342073 - seems like the best option at the moment

**Comment by thekiba** [comment]
We've just released **@tonconnect/ui-react@2.1.0** with **React 19** support via [PR #330](https://github.com/ton-connect/sdk/pull/330). This update should resolve the compatibility issues you reported.

Please update to the latest version and let us know if you encounter any issues with the update.
